version: "3"
services:
  nginx_http:
    image: nginx
    container_name: vue-practice
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    ports:
      - "3968:80"
    tty: true